# Exported from Render on 2026-04-22T12:22:06Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Sparkly
      runtime: docker
      repo: https://github.com/IErilov/mes
      plan: free
      region: ohio
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
